# Common role

---

- name: Set package holds
  dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
    - "{{held_packages}}"
  tags:
    - dpkg

- name: Install standard software
  apt:
    state: present
    pkg:
    - less
    - bash
    - rsync
    - sudo-ldap
    - unattended-upgrades
    - apt-listchanges
    - aptitude
    - debconf-utils
    - python
    - python-simplejson
    - dstat
    - pv
    - tcpdump
    - nmap
    - screen
    - ncdu
    - zsh
    - htop
    - vim
    - postfix
    - ack-grep
  when: ansible_os_family == 'Debian'
  tags:
    - debian
    - apt
    - common

- name: Enable auto-installing security updates on Debian
  debconf: name='unattended-upgrades' question='enable_auto_updates' value='true' vtype='select'
  tags:
    - debian
    - common
    - debconf
    - unattended

- name: Set directory permissions
  file: state=directory owner=root group=root mode=0700 path={{item}}
  with_items:
    - /root
    - /root/.ssh
  tags:
    - directory
    - pubkey
    - debian

- name: Set vim as default editor
  alternatives: name=editor path=/usr/bin/vim.basic
  tags:
    - editor
    - debian

- name: Template various files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner|default('root')}}"
    group: "{{item.group|default('root')}}"
    mode: "{{item.mode|default('0600')}}"
  notify: "{{item.handler|default('dummy_handler')}}"
  with_items:
    - { src: "vimrc.local.j2", dest: "/etc/vim/vimrc.local", mode: "0644" }
    - { src: "authorized_keys-root.j2", dest: "/root/.ssh/authorized_keys", mode: "0600" }
    - { src: "limit-unstable.j2", dest: "/etc/apt/preferences.d/limit-unstable" }
    - { src: "sshd_config.j2",  dest: "/etc/ssh/sshd_config", notify: "reload sshd" }
    - { src: "default-grub.j2",  dest: "/etc/default/grub", notify: "update grub" }
    - { src: "issue", dest: "/etc/issue", mode: "0644" }
    - { src: "issue.net", dest: "/etc/issue.net", mode: "0644" }
    - { src: "resolv.conf.j2", dest: "/etc/resolv.conf", mode: "0644" }
    - { src: "postfix-main-cf.j2", dest: "/etc/postfix/main.cf", notify: "reload postfix" }
    - { src: "postfix-virtual.j2", dest: "/etc/postfix/virtual", notify: "postmap virtual" }
    - { src: "aliases.j2", dest: "/etc/aliases", notify: "newaliases" }
    - { src: "mailname.j2", dest: "/etc/mailname", notify: "reload postfix" }
    - { src: "ntp.conf.j2", dest: "/etc/ntp.conf", mode: "0644", notify: "reload ntpd" }

- name: Configure 'unstable' repository for debian
  apt_repository:
    repo: "deb http://ftp.nl.debian.org/debian/ unstable main"
    state: present
    filename: "debian-unstable-main"
  when:
    - "'Debian' in ansible_distribution"
    - unstable_repo|bool
  tags:
    - unstable
    - debian

- name: Create ssh-ed25519 key for root user
  openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    comment: "root@{{inventory_hostname}}"
